### ISSUE TITLE
Unable to un-bind Autosleep service from an application

### ISSUE THREAD

**Issue by SudarsananRengarajan** [Orange-OpenSource/autosleep#255] opened 2016-10-04 15:54 UTC
Hi,

Am unable to un-bind Autosleep service from an application either via UI/CLI.
I have created the service instance using the below parameter from UI
exclude-from-auto-enrollment 
idle-duration = PT5M (5 mins)

Error while trying to unbind: "Service could not be deleted from the application"

Note: Due to this am unable to delete the application as well.

Regards,
Sudarsanan R

**Comment by gberche-orange** [comment] 2016-10-11 08:39
@SudarsananRengarajan 

Can you please copy the exact "cf create-service" command you used when creating the service instance, and the unbind and observed failure output ?

If the `'{"auto-enrollment": "forced"}'` option was paased during service instance provisionning, then the **service instance deletion** is rejected as intended, see https://github.com/cloudfoundry-community/autosleep#lockauto-enrollment for more details as well as https://github.com/cloudfoundry-community/autosleep/blob/develop/acceptance/5_forced_enrollment.robot#L41-L49

If not, please obtain log output from your autosleep service provider as to diagnose and reproduce the issue (see https://github.com/cloudfoundry-community/autosleep/blob/develop/doc/publish.md for operators documentation and https://github.com/cloudfoundry-community/autosleep/blob/develop/manifest.tmpl.yml#L19 to tune log verbosity)

**Comment by gberche-orange** [comment] 2016-10-19 15:16
@SudarsananRengarajan ping

any more details, or should we close this issue ?

**Comment by SudarsananRengarajan** [comment] 2016-10-19 16:20
Hi,

Sorry for the delayed response. I was able to purge the service instance. you can close the issue. Thanks for the response and support.

Regards,
Sudarsanan R

**Comment by gberche-orange** [comment] 2016-10-19 16:55
thanks @SudarsananRengarajan

**Closed as completed by gberche-orange** 2016-10-19 16:55 UTC
